#!/usr/bin/env python
from os import listdir as ls
from os import remove
from os.path import isfile
from shutil import rmtree
protected = ['.git', 'clear', 'sol', 'data', 'run', 'unfinished', 'support-files']
cur = '.'
trash = []


for f in ls(cur):
    if f not in protected:
        trash.append(f)

if trash:
    print 'Detect those files and folds'
    for i in trash:
        print i
    x = raw_input("Press 'y/n' to delete...")
    if x == 'y':
        for i in trash:
            print 'rm', i
            if isfile(i):
                remove(i)
            else:
                rmtree(i)
print 'Clean!'
