#!/usr/bin/env python
# -*-: encoding: utf-8 -*-
from tinydb import TinyDB, Query
from shutil import rmtree, move
import argparse
import re
import json

config = json.load(open("support-files/config.json", "r"))


def work():
    db = TinyDB('support-files/db.json')
    parser = argparse.ArgumentParser()
    parser.add_argument("problem")
    args = parser.parse_args()
    pid = args.problem
    x = raw_input("Finish and delete [%s]? y/n" % pid)
    if x != 'n':
        move('%s/%s.cpp' % (pid, pid), '%s/%s.cpp' % (config['directory'], pid))
        rmtree(pid)
    if re.findall("^\d+", pid):
        cid = int(re.findall("^\d+", pid)[0])
        idx = pid[len(str(cid)):]
        q = Query()
        db.update({'isSolved': True}, (q.contestId == cid) & (q.index == idx))
    print "Done!"

if __name__ == "__main__":
    work()
